### PR TITLE
Added Darkmode 

### PR DESCRIPTION
**Pull request by chinmaym07**
I tried a lot of different ways to do this but unfortunately had to adopt this method.Please Review it.
Thanks a lot for assigning me this issue. :

Screen Shot 2020-10-17 at 01 44 24
Screen Shot 2020-10-17 at 01 45 03

### CODE REVIEW

**Comment by abhaynikam** [comment]
@chinmaym07 Looks good to me. A small change request. The social icons shown in the footer. Can you invert the color of those as well?

**Comment by abhaynikam** [comment]
Just saw the deployed app. Love your work ❤️ . Thank you.

Some small suggestions
- If possible, let's make the switch size smaller.
- The color of the title text `Nice Blogs` -> `rgb(217, 194, 194)` and switch should be the same when dark mode is enabled.
- If possible, we can either try to use [gatsby-plugin-dark-mode](https://www.gatsbyjs.com/plugins/gatsby-plugin-dark-mode/). It would be easier to maintain the state of the theme across all pages for dark mode and code would look more cleaner.
- The blog page needs some tweak for dark mode. Refer follow screenshot:
blog-page

**Comment by chinmaym07** [comment]
Ohh Sorry.!! I will implement this and will update you.
Thanks a lot for your valuable feedback.!

**Comment by abhaynikam** [comment]
@chinmaym07 No worries. Here is my little attempt to resolve this issue: https://github.com/abhaynikam/gatsby-nice-blog/commit/4a8600c27f51b72dc2ef65e8247f195d04c328b1

Feel free to cherry-pick the code. Also, I would love to add you as a contributor in the readme page. You can open another PR for same with link to your Profile. Happy Coding 😊  

Also, instead of a switch, we can try adding sun/moon icon. Similar to: https://novela.narative.co/.

**Comment by abhaynikam** [comment]
Closed in favor of #6

**Pull request closed without merging**
